<?php
/**
 * Created by PhpStorm.
 * User: AkKe
 * Date: 4/27/2017
 * Time: 4:38 PM
 */

namespace app\components;
use yii\base\Widget;
class FirstWidget extends Widget {
    public $mes;
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        ob_start();
//        if($this->mes === null){
//            $this->mes ='First Widget';
//        }
    }

    public function run()
    {
        $content = ob_get_clean();
        return "<h1>$content</h1>";
    }
}